gg.toast('@MrTermux')
print('bazio bega')

gg.searchNumber(" 11349;1650 ", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber(" 1650 ", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000)
gg.editAll("2144061856 ", gg.TYPE_DWORD)
gg.clearResults()
gg.toast("sabr konid")
gg.searchNumber(" 11349;650 ", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber(" 650 ", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(5000)
gg.editAll("1 ", gg.TYPE_DWORD)
gg.clearResults()
gg.toast("ok")
print('@MrTermux')
